# Generated by Django 3.2.5 on 2022-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aalim', '0002_auto_20220626_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
