# Generated by Django 3.2.13 on 2022-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aalim', '0003_student_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_number',
            new_name='parent_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
